In [89]:
import pandas as pd
import ast

def convertColumn(x):
    content = ast.literal_eval(x) if isinstance(x, str) else x
    result = sum(content) / len(content) if isinstance(content, list) else content
    return result
data = pd.read_csv("Quantitative_data.csv")
# Split the string, convert to numeric values, and calculate the average
data['resolution_quantitative'] = data['rcsb_entry_info_resolution_combined'].apply(lambda x: convertColumn(x))

# Extract the header as a DataFrame with one row
numeric_column_names = data.select_dtypes(include='number').columns
df = data[numeric_column_names]
# remove _id columns
# Remove columns with "_id" in their headers
filtered_columns = [col for col in df.columns if '_id' not in col]

df[filtered_columns]

C:\Users\awotoroe\AppData\Local\Temp\ipykernel_16108\884165788.py:8: DtypeWarning: Columns (11,14,129,131,141,145,149,167,168,169,170,171,172,173,174,175,179,180,184,185,187,188,189,193,194,195,196,197,198,202,203,204,205,206,207,208,209,210,213,234,243,344,400,401,403,404,405,407,414,420,451,452,461,463,464,467,480,481,483,484,496,525,527,529,535,544,547,563,568,569,570,571,572,576,577,580,582,584,585,586,587,588,589,594,596,597,598,599,601,602,603,604,605,609,610,612,613,617,618,619,622,637,642,659,662,664,666,667,668,669,670,673,674,679,680,681,683,685,686,687,688,689,697,707,709,711,719) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("Quantitative_data.csv")

,Unnamed: 0,Unnamed: 0_x,Unnamed: 0_1,Unnamed: 0_y,cell_angle_alpha,cell_angle_beta,cell_angle_gamma,cell_length_a,cell_length_b,cell_length_c,...,pdbx_serial_crystallography_measurement_xfel_pulse_repetition_rate,pdbx_serial_crystallography_measurement_pulse_energy,pdbx_serial_crystallography_measurement_photons_per_pulse,em2d_crystal_entity_angle_gamma,em2d_crystal_entity_c_sampling_length,em2d_crystal_entity_length_a,em2d_crystal_entity_length_b,em2d_crystal_entity_length_c,bibliography_year,resolution_quantitative
0,0,0,0,0,90.0,90.0,90.0,99.40,210.30,233.10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1994,3.50
1,1,1,1,1,90.0,90.0,90.0,99.57,209.80,235.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1995,3.40
2,2,2,2,2,90.0,90.0,90.0,99.40,210.30,233.10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1995,3.10
3,3,3,3,3,90.0,90.0,90.0,98.65,204.99,221.96,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001,2.61
4,4,4,4,4,90.0,90.0,90.0,98.87,207.46,221.98,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001,3.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3130,3130,3135,3118,3118,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,2.94
3131,3131,3136,3119,3119,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,2.50
3132,3132,3137,3120,3120,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,2.75
3133,3133,3138,3121,3121,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022,2.74
3134,3134,3139,3122,3122,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023,2.50

In [90]:
colco = [col for col in df[filtered_columns].columns if '0' not in col]

Quantitative = df[colco]
Quantitative.to_csv("NewQuantitative.csv")

In [91]:
# Extract the header as a DataFrame with one row
numeric_column_names_ = data.select_dtypes(exclude='number').columns
df_ = data[numeric_column_names_]

In [121]:
colco_ = [col for col in df_.columns if '0' not in col and '_id' not in col]

In [122]:
len(colco_)

304

In [123]:
data[colco_]
NonQuantitative = data[colco_]
NonQuantitative.to_csv("NewNonQuantitative.csv")

In [136]:
# manually remove column that doesn't contribute to anything...


	
retained_columns_from_non_numeric = [
    "Group", "Species", "Subgroup", "Taxonomic Domain",	
    "Expressed in Species", 
    "Secondary Bibliogrpahies", 
    "rcsb_entry_info_experimental_method", 	
    "rcsb_entry_info_polymer_composition", 
    "rcsb_entry_info_selected_polymer_entity_types", 
    "symmetry_space_group_name_hm",
    "diffrn_radiation_pdbx_scattering_type",
    "diffrn_radiation_pdbx_monochromatic_or_laue_ml",	
    "exptl_method",
    "diffrn_detector_detector", 
    "diffrn_source_source"
]

In [137]:
retained_df = NonQuantitative[retained_columns_from_non_numeric]

# Display the DataFrame with retained categorical columns
retained_df.columns

Index(['Group', 'Species', 'Subgroup', 'Taxonomic Domain',
       'Expressed in Species', 'Secondary Bibliogrpahies',
       'rcsb_entry_info_experimental_method',
       'rcsb_entry_info_polymer_composition',
       'rcsb_entry_info_selected_polymer_entity_types',
       'symmetry_space_group_name_hm', 'diffrn_radiation_pdbx_scattering_type',
       'diffrn_radiation_pdbx_monochromatic_or_laue_ml', 'exptl_method',
       'diffrn_detector_detector', 'diffrn_source_source'],
      dtype='object')

In [138]:
retained_df.to_csv("retained_df.csv")

In [139]:
# get other columns not really needed
all_non_numeric_colums = NonQuantitative.columns
retained_columns = retained_df.columns
# Subtract selected columns from all columns
remaining_columns = [col for col in all_non_numeric_colums if col not in retained_columns]

In [141]:
not_really_needed = NonQuantitative[remaining_columns]

In [142]:
not_really_needed.to_csv("Non_numeric_not_needed.csv")